{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kaytoo.fullname" . }}
  labels:
    {{- include "kaytoo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.slackBotToken }}
  SLACK_BOT_TOKEN: {{ .Values.secrets.slackBotToken | quote }}
  {{- end }}
  {{- if .Values.secrets.slackAppToken }}
  SLACK_APP_TOKEN: {{ .Values.secrets.slackAppToken | quote }}
  {{- end }}
  {{- if .Values.secrets.matrixAccessToken }}
  MATRIX_ACCESS_TOKEN: {{ .Values.secrets.matrixAccessToken | quote }}
  {{- end }}
  {{- if .Values.secrets.mattermostToken }}
  MATTERMOST_TOKEN: {{ .Values.secrets.mattermostToken | quote }}
  {{- end }}
  OPENSEARCH_USERNAME: {{ .Values.secrets.opensearchUsername | quote }}
  OPENSEARCH_PASSWORD: {{ .Values.secrets.opensearchPassword | quote }}
  LLM_API_KEY: {{ .Values.secrets.llmApiKey | quote }}
{{- end }}

