export const candidateFields = {
  bytes: ['flow.bytes', 'flow.bytes.delta', 'flow.bytes.total', 'network.bytes'],
  srcIp: ['flow.client.ip.addr', 'source.address', 'source.ip', 'flow.src.ip.addr'],
  dstIp: ['flow.server.ip.addr', 'destination.address', 'destination.ip', 'flow.dst.ip.addr'],
  srcPort: ['flow.client.port', 'source.port'],
  dstPort: ['flow.server.port', 'destination.port'],
  proto: ['l4.proto.name', 'network.transport'],
  podName: [
    'source.k8s.pod.name',
    'flow.client.k8s.pod.name',
    'flow.src.k8s.pod.name',
    'kubernetes.pod.name',
    'k8s.pod.name',
    'orchestrator.resource.name',
  ],
  packets: ['flow.packets.delta', 'network.packets', 'flow.packets'],
  availabilityZone: ['cloud.availability_zone', 'cloud.region', 'availability_zone'],
  dstPodName: [
    'destination.k8s.pod.name',
    'flow.server.k8s.pod.name',
    'flow.dst.k8s.pod.name',
    'destination.kubernetes.pod.name',
    'kubernetes.pod.name',
  ],
  dstNamespace: [
    'destination.k8s.namespace.name',
    'flow.server.k8s.namespace.name',
    'flow.dst.k8s.namespace.name',
    'destination.kubernetes.namespace',
    'kubernetes.namespace',
  ],
  dstServiceName: [
    'destination.k8s.service.name',
    'flow.server.k8s.service.name',
    'flow.dst.k8s.service.name',
    'kubernetes.service.name',
    'destination.service.name',
  ],
  srcNode: [
    'source.k8s.node.name',
    'flow.client.k8s.node.name',
    'flow.src.k8s.node.name',
    'kubernetes.node.name',
    'source.node.name',
    'host.name',
  ],
  dstNode: [
    'destination.k8s.node.name',
    'flow.server.k8s.node.name',
    'flow.dst.k8s.node.name',
    'destination.node.name',
    'host.name',
  ],
  durationMs: ['event.duration', 'flow.duration', 'network.duration'],
  tcpFlags: ['flow.tcp.flags.bits', 'tcp.flags', 'flow.tcp.flags', 'network.tcp.flags'],
  ipVersion: ['network.type', 'network.iana_number', 'ip.version', 'ip.version.name'],
  clientNamespace: [
    'source.k8s.namespace.name',
    'flow.client.k8s.namespace.name',
    'flow.src.k8s.namespace.name',
    'kubernetes.namespace',
    'kubernetes.namespace.name',
    'k8s.namespace.name',
    'source.namespace',
    'orchestrator.namespace',
  ],
  srcDisplayName: [
    'source.k8s.pod.name',
    'source.k8s.service.name',
    'source.k8s.deployment.name',
    'source.k8s.statefulset.name',
    'source.k8s.node.name',
    'process.executable.name',
    'source.container.name',
    'source.k8s.container.name',
    'flow.client.k8s.pod.name',
    'flow.src.k8s.pod.name',
    'flow.client.host.name',
    'flow.src.host.name',
    'kubernetes.pod.name',
    'host.name',
  ],
  dstDisplayName: [
    'destination.k8s.pod.name',
    'destination.k8s.service.name',
    'destination.k8s.deployment.name',
    'destination.k8s.node.name',
    'flow.server.k8s.pod.name',
    'flow.dst.k8s.pod.name',
    'destination.kubernetes.pod.name',
    'flow.server.host.name',
    'flow.dst.host.name',
  ],
};
